#
# Copyright (C) 2018 Cumulus Networks, Inc. All rights reserved
# 
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# 
# https://www.debian.org/legal/licenses/mit
# 
---
- set_fact:
    myvars: "{{ switchvars[inventory_hostname] }}"

- name:  Unnumbered BGP routing (v4 & V6) to the hosts and spines
  nclu:
    commands:
    - add bgp autonomous-system {{ myvars.ASN }}
    - add loopback lo ip address {{ myvars.V4 }}/32
    - add bgp router-id {{ myvars.V4 }}
    - add loopback lo ipv6 address {{ myvars.V6 }}/128
    - add bgp ipv4 unicast network {{ myvars.V4 }}/32
    - add bgp ipv6 unicast network {{ myvars.V6 }}/128
    - add bgp bestpath as-path multipath-relax
    - add bgp neighbor {{ UPLINK_IFS }} interface remote-as external
    - add bgp ipv4 unicast neighbor {{ UPLINK_IFS }} activate
    - add bgp ipv6 unicast neighbor {{ UPLINK_IFS }} activate
    - add interface {{ UPLINK_IFS }} mtu 9000
    - add bgp neighbor {{ ACCESS_IFS }} interface remote-as external
    - add bgp ipv4 unicast neighbor {{ ACCESS_IFS }} activate
    - add bgp ipv6 unicast neighbor {{ ACCESS_IFS }} activate
    - add interface {{ ACCESS_IFS }} mtu 9000
    atomic: true
    description: "unnumbered BGP leaf"
- nclu:
    commands:
    - add bgp neighbor {{ LEAF_INET_IFS }} interface remote-as external
    - add bgp ipv4 unicast neighbor {{ LEAF_INET_IFS }} activate
    - add bgp ipv6 unicast neighbor {{ LEAF_INET_IFS }} activate
    - add interface {{ LEAF_INET_IFS }} mtu 9000
    atomic: true
    description: "unnumbered BGP to Internet"
  when: (inventory_hostname  == "leaf01") or (inventory_hostname == "leaf02")
...
